# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .vcn import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "oci-vcn",
  "mod": "index",
  "fqn": "lbrlabs_pulumi_oci_vcn",
  "classes": {
   "oci-vcn:index:Vcn": "Vcn"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "oci-vcn",
  "token": "pulumi:providers:oci-vcn",
  "fqn": "lbrlabs_pulumi_oci_vcn",
  "class": "Provider"
 }
]
"""
)
