# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: oci-vcn
resources:
  oci-vcn:index:Vcn:
    isComponent: true
    inputProperties:
      compartmentId:
        type: string
        description: Compartment ID to deploy into
      cidrBlock:
        type: string
        description: "Cidr block to use for VCN"
        plain: true
      dnsLabel:
        type: string
        description: "DNS labels for VCN"
      ipv6Enabled:
        type: boolean
        description: "Enable ipv6 for VCN"
      numberOfSubnets:
        type: number
        description: "Number of public and private subnets to create"
        plain: true
      createInternetGateway:
        type: boolean
        plain: true
      createServiceGateway:
        type: boolean
        plain: true
      createNatGateway:
        type: boolean
        plain: true
    requiredInputs:
    - compartmentId
    - cidrBlock
    properties:
      vcnId:
        type: string
        description: The ID of the VCN.
      publicSubnetIds:
        type: array
        description: The IDs of the public subnets.
        items:
          type: string
      privateSubnetIds:
        type: array
        description: The IDs of the private subnets.
        items:
          type: string
      internetGatewayId:
        type: string
        description: The ID of the internet gateway.
      serviceGatewayId:
        type: string
        description: The ID of the service gateway.
      natGatewayId:
        type: string
        description: The ID of the NAT gateway.
    required: 
    - vcnId
    - publicSubnetIds
    - privateSubnetIds
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Oci: 0.*
    rootNamespaces: Lbrlabs.PulumiPackage
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/lbrlabs/pulumi-oci-vcn/sdk/go/vcn
  nodejs:
    dependencies:
      "@pulumi/oci": "^0.5.0"
    devDependencies:
      typescript: "^3.7.0"
    packageName: "@lbrlabs/pulumi-oci-vcn"
  python:
    packageName: lbrlabs_pulumi_oci_vcn
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-oci: ">=0.0.0,<1.0.0"
