# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: oci-vcn
resources:
  oci-vcn:index:Vcn:
    isComponent: true
    inputProperties:
      compartmentId:
        type: string
        description: Compartment ID to deploy into
      cidrBlock:
        type: string
        description: "Cidr block to use for VCN"
        plain: true
    requiredInputs:
    - compartmentId
    - cidrBlock
    properties:
      vcn:
        "$ref": "/oci/v0.5.0/schema.json#/resources/oci:Core%2Fvcn:Vcn"
        description: The bucket resource.
    required: 
    - vcn
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Oci: 0.*
    rootNamespaces: Lbrlabs.PulumiPackage
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/lbrlabs/pulumi-oci-vcn/sdk/go/vcn
  nodejs:
    dependencies:
      "@pulumi/oci": "^0.5.0"
    devDependencies:
      typescript: "^3.7.0"
    packageName: "@lbrlabs/pulumi-oci-vcn"
  python:
    packageName: lbrlabs_pulumi_oci_vcn
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-ic: ">=0.0.0,<1.0.0"
